In [7]:
import pandas as pd
import numpy as np

In [10]:
stops = pd.read_table(r"J:\My Drive\gtfs_to_transcad\GTFS_Recap_-_Fall_2020\stops.txt",sep=',')
shapes = pd.read_table(r"J:\My Drive\gtfs_to_transcad\GTFS_Recap_-_Fall_2020\shapes.txt", sep=',')
stops

,Unnamed: 0,stop_id,stop_code,stop_name,stop_desc,platform_code,platform_name,stop_lat,stop_lon,zone_id,stop_address,stop_url,level_id,location_type,parent_station,wheelchair_boarding,municipality,on_street,at_street,vehicle_type
0,0,1,1.0,Washington St opp Ruggles St,NaN,NaN,NaN,42.330957,-71.082754,ExpressBus-Downtown,NaN,https://www.mbta.com/stops/1,NaN,0,NaN,1,Boston,Washington Street,Ruggles Street,3.0
1,1,10,10.0,Theo Glynn Way @ Newmarket Sq,NaN,NaN,NaN,42.330555,-71.068787,LocalBus,NaN,https://www.mbta.com/stops/10,NaN,0,NaN,1,Boston,Theodore Glynn Way,Newmarket Square,3.0
2,2,10000,10000.0,Tremont St opp Temple Pl,NaN,NaN,NaN,42.355692,-71.062911,LocalBus,NaN,https://www.mbta.com/stops/10000,NaN,0,NaN,1,Boston,Tremont Street,Temple Place,3.0
3,3,10003,10003.0,Albany St opp Randall St,NaN,NaN,NaN,42.331591,-71.076237,LocalBus,NaN,https://www.mbta.com/stops/10003,NaN,0,NaN,0,Boston,Albany Street,Randall Street,3.0
4,4,10005,10005.0,Albany St opp E Concord St,NaN,NaN,NaN,42.335017,-71.071280,LocalBus,NaN,https://www.mbta.com/stops/10005,NaN,0,NaN,1,Boston,Albany Street,East Concord Street,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7342,9441,70163,70163.0,Woodland,Woodland - Green Line - (D) Riverside,NaN,Riverside,42.333372,-71.244303,RapidTransit,NaN,https://www.mbta.com/stops/place-woodl,level_ground,0,place-woodl,1,Newton,NaN,NaN,0.0
7343,9445,70124,70124.0,Warren Street,Warren Street - Green Line - Park Street & North,NaN,Park Street & North,42.348285,-71.140436,RapidTransit,NaN,https://www.mbta.com/stops/place-wrnst,level_median,0,place-wrnst,2,Boston,NaN,NaN,0.0
7344,9446,70125,70125.0,Warren Street,Warren Street - Green Line - (B) Boston College,NaN,Boston College,42.348819,-71.140051,RapidTransit,NaN,https://www.mbta.com/stops/place-wrnst,level_median,0,place-wrnst,2,Boston,NaN,NaN,0.0
7345,9448,74613,74613.0,World Trade Center,World Trade Center - Silver Line - Airport/Des...,NaN,Airport/Design Center/Chelsea,42.348630,-71.042460,SLWaterfrontNonLogan,NaN,https://www.mbta.com/stops/place-wtcst,level_-1_platform,0,place-wtcst,1,Boston,Waterfront,NaN,3.0
7346,9449,74615,74615.0,World Trade Center,World Trade Center - Silver Line - South Station,NaN,South Station,42.348630,-71.042460,SLWaterfrontNonLogan,NaN,https://www.mbta.com/stops/place-wtcst,level_-1_platform,0,place-wtcst,1,Boston,Waterfront,NaN,3.0

In [11]:
#stops = stops.query('stop_code==stop_code & vehicle_type==vehicle_type')
#stops.to_csv(r"C:\Users\matkinson.AD\Downloads\GTFS_Recap_-_Fall_2020\stops.txt")
shapes

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,010085,42.329848,-71.083876,10001,NaN
1,010085,42.329788,-71.083268,10002,NaN
2,010085,42.330089,-71.083198,10003,NaN
3,010085,42.330296,-71.083161,10004,NaN
4,010085,42.330493,-71.083112,10005,NaN
...,...,...,...,...,...
279870,cf00002,41.655984,-70.279659,2534,NaN
279871,cf00002,41.655724,-70.279809,2535,NaN
279872,cf00002,41.655406,-70.279966,2536,NaN
279873,cf00002,41.655173,-70.280072,2537,NaN
279874,cf00002,41.654898,-70.280190,2538,NaN

In [15]:
stop_shapes = stops[['stop_id','stop_lat','stop_lon']].merge(
    shapes[['shape_pt_lat','shape_pt_lon']], how='left',
    left_on = ['stop_lat','stop_lon'],
    right_on=['shape_pt_lat','shape_pt_lon'], indicator=True)

print(len(stops))
print(len(stops[stop_shapes._merge == 'left_only']))

7347
7189

C:\Users\matkinson.AD\AppData\Local\Temp\ipykernel_19908\3958575169.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(stops[stop_shapes._merge == 'left_only']))